MegEngine/Documentation

examples/models/resnet.py
examples/models/utils.py

Implementate the resnest acording to https://arxiv.org/pdf/2004.08955.pdf and https://github.com/zhanghang1989/ResNeSt/tree/master/resnest/torch. Also modified the split from megengine.functional to fix some bug.

Add resnest and modified split

---

.github/workflows/github-pages-deploy.yml
.github/workflows/sphinx-build.yml
CONTRIBUTING.md

This is also a test for `rebase` (which might cause `push --force`) and `main` branch protection rules.

actions: make github action workflow run correctly

---

source/user-guide/load-and-run.rst

refactor: run profile_analyze as a script

---

.github/workflows/github-pages-deploy.yml

update CI python version from 3.6 to 3.7

ci: update github deployment python version

---

source/conf.py
source/development/contribute-to-docs/commit-message.rst
source/reference/quantization.rst
source/user-guide/model-development/dump.rst
source/user-guide/tools/load-and-run.rst
source/user-guide/tools/module-stats.rst
source/user-guide/tools/runtimeopr.rst

Add edit page on github and pre/next button

---

source/development/contribute-to-docs/restructuredtext.rst

Refs: https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#math

docs(rst): add sphinx directives examples

---

Makefile
source/development/contribute-to-docs/build-the-doc-locally.rst
source/development/contribute-to-docs/commit-message.rst
source/development/contribute-to-docs/index.rst
source/development/contribute-to-docs/python-docstring-style-guide.rst
source/development/contribute-to-docs/restructuredtext.rst

Docstring best practice 还没有写...

docs(dev): add more details about API and docstring

---

source/user-guide/model-compression/quantization.rst

MegEngine/Models --> https://github.com/MegEngine/Models/tree/master/official/quantization

Replace MegEngine/Models with links

---

source/development/architecture-design.rst

目前只是一份初稿，如果格式正确希望先合入，后续随着更多的文档的涌入再继续调整

docs(development): add docs for megengine architecture

---

source/user-guide/tools/stats.rst

update examples of module-stats tools.

update module-stats tools

---

source/user-guide/model-development/jit/trace.rst

docs(trace): add DTRConfig

---

source/development/architecture-design.rst
source/user-guide/model-development/dtr/index.rst

 docs(dtr): update DTR v1.5

---

.gitpod.yml
source/development/contribute-to-docs/index.rst

It seems that gitpod-io is really powerful.

feat: support gitpod prebuild

---

source/reference/comparison.rst
source/user-guide/index.rst
source/user-guide/transfer-from/index.rst
source/user-guide/transfer-from/numpy.rst
source/user-guide/transfer-from/pytorch.rst

We need write more contents in our transfer guide later.

docs(guide): add transfer guide for user from other framework

---

source/user-guide/deployment/lite/cpp.rst
source/user-guide/deployment/lite/example.rst
source/user-guide/deployment/lite/index.rst
source/user-guide/deployment/lite/python.rst
source/user-guide/deployment/lite/third-party.rst
source/user-guide/index.rst
source/user-guide/install/index.rst

add lite doc

---

source/development/behind/compnode.rst
source/development/behind/index.rst

#258 
求看一下是不是写的有点不那么 “幕后揭秘” @xxr3376 @MegChai

docs(explaination): add compnode explanation

---

source/user-guide/index.rst
source/user-guide/tools/customop.rst

add custom op user guide documentation
@MegChai please kindly review

docs(source/user-guide): add custom op user guide

---

.gitattributes
source/_static/images/Simplified-illustration-of-the-AlexNet-architecture.pbm
source/user-guide/model-development/module/design.rst
source/user-guide/model-development/module/index.rst

User guide for `megengine.module`
Close #231 #232

docs(guide): add module guide

---

source/user-guide/model-development/distributed/index.rst

修改分布式的文档，推荐使用Module.tensors同步参数，避免漏写```dist.bcast_list_(net.buffers())的情况```

docs(dist): use Module.tensors to broadcast states

---

source/reference/comparison.rst
source/reference/functional.rst

应该在 1.6 Wheel 包发布之后合入，不然会导致 sphinx build warning

docs(api): hint user call with loss/metric/vision nn.func_name

---

source/reference/index.rst
source/reference/traced_module.rst

docs(api): add traced module api

---

source/_static/images/dtype_promotion_lattice.png
source/_static/images/dtype_promotion_megengine.png
source/user-guide/model-development/tensor/dtype.rst

docs(guide): add type promotion rule in dtype guide

---

.github/workflows/deploy-dev.yml

refactor(workflow): update megengine build script

---

source/user-guide/model-development/functional/general-operations.rst

Fix typoo #302 cc @applepi-icpc

docs(functional): fix general operations typo

---

source/reference/random.rst

docs(reference): add shuffle API

---

locales/en/LC_MESSAGES/user-guide/tools/load-and-run.po
locales/zh_CN/LC_MESSAGES/user-guide/tools/load-and-run.po
locales/zh_TW/LC_MESSAGES/user-guide/tools/load-and-run.po
source/user-guide/tools/load-and-run.rst

Rebased on `main` branch. Close #311

docs(lar): update load and run usage

---

source/user-guide/model-development/traced_module/quick-start.rst

docs(traced_module): update traced_module serialization

---

source/user-guide/model-development/optimizer/index.rst

在教别人的时候发现的问题，这里的 GradManager 没构造，这份代码根本没法正常运行。

fix: initialize GradManager first

---

source/development/docs/build-the-doc-locally.rst

Co-authored-by: scarlettliu920 <22585418@qq.com>

docs(dev): fix typos in build the doc page

---

source/user-guide/deployment/lite/advance/cv-examples.rst
source/user-guide/deployment/lite/advance/index.rst

增加了两个cv的example的简单文档
@MegChai please review，thanks！

Add lite cv example

---

source/reference/environment-variables.rst

添加fastrun cache配置相关的两个环境变量，以便用户在默认cache配置不可用时更改配置

docs(environ): add fastrun cache env vars

---

source/user-guide/model-development/optimizer/index.rst

doc: Add lr parameter to SGD

---

source/user-guide/transfer-from/pytorch.rst

相关信息：
- 关于 CUDA fork 导致 error 的问题，可能需要在分布式的文档里面好好说道说道，就不在这个页面改了。
Co-authored-by: FateScript <wangfeng19950315@163.com>
Co-authored-by: P2Oileen <p2oileen@whu.edu.cn>

docs(guide): add more cases when comparing with PyTorch

---

source/getting-started/deploy/android.rst
source/getting-started/deploy/index.rst

先临时根据基本思路糊了一版，欢迎 Review,
（ 预览源代码不直观的话，可以借助 2L 的 gitpod-io, 或者看 CI build 出来的 artifact
@xxr3376 @FateScript

docs(tutorial): add megengine lite android tutorial

---

source/reference/deprecated.rst

docs(reference): add alternative interface for deprecated api(#405)

---

source/reference/lite/network.rst

docs(api/lite): add lite network api doc

---

source/user-guide/model-development/amp/index.rst
source/user-guide/model-development/amp/nhwc.rst

docs(user-guide): add nhwc amp docs

---

scripts/coverage.py

Please take a look, thx @xxr3376

misc: add api coverage test script

---

examples/beginner/conv-network-cifar10.py
examples/beginner/linear-classification-fashion.py
examples/beginner/linear-classification.py
examples/beginner/linear-regression.py
examples/beginner/neural-network-cifar10.py
examples/beginner/neural-network.py
examples/quick-start.py
source/getting-started/beginner/convolutional-neural-network.rst
source/getting-started/beginner/linear-classification.rst
source/getting-started/beginner/linear-regression.rst
source/getting-started/quick-start.rst

Solve #459  make code in quick start runnable again

---

scripts/coverage.py

scirpt: handle with deprecated APIs

---

.github/workflows/deploy.yml
scripts/oss/gen_version.py
source/development/docs/maintainer-responsibility.rst

ci: generate version.json automatically

---

.github/workflows/build-dev.yml
.github/workflows/deploy-dev.yml

ci: add test and bot webhook

---

source/user-guide/deployment/lite/quick-start/cpp.rst

fix: fix Documentation git url

---

locales/en/LC_MESSAGES/development/docs/build-the-doc-locally.po
locales/zh_CN/LC_MESSAGES/development/docs/build-the-doc-locally.po
source/development/docs/build-the-doc-locally.rst
source/user-guide/deployment/lite/advance/binary-optimize.rst

@Wanwan1996    pls help review

opt midout doc

---

source/user-guide/model-development/data/dataset.rst
source/user-guide/model-development/module/design.rst

feat(data): add concatset doc of map-dataset
